media: assets/img
content:
  - name: ru-posts
    label: RU articles
    type: collection
    path: content/ru-lang/kharkiv
    fields:
      - { name: tabTitle, lable: Название вкладки, type: string }
      - { name: title, lable: Заголовок, type: sting }
      - { name: description, lable: Описание, type: string }
      - { name: image, lable: Картинка, type: image }
      - { name: imageText, lable: Описание картинки, type: string }
      - { name: ratingAvarage, lable: Оценка статьи, type: string }
      - { name: rating, lable: Сколько человек оценили, type: number }
      - {
          name: reviewType,
          lable: Тип отзывов,
          type: select,
          options: { values: [alk-1, alk-2, kod-1, kod-2] },
        }
      - { name: body, lable: Текст статьи, type: rich-text}
